parameters:
  ServiceConnection:

stages:
- stage: ApiBuild
  displayName: Build Image
  jobs:
  - job: build_image
    displayName: Build Image
    pool:
      name: DAS - Continuous Integration Agents

    steps:
    - task: UseGitVersion@5
      inputs:
        versionSpec: 5.x
        useConfigFile: true
        configFilePath: GitVersion.yml
    - template: azure-pipelines-templates/build/step/dockerfile-build.yml@das-platform-building-blocks
      parameters:
        ContainerRegistryName: $(PublicAcrName)
        ServiceConnection: ${{ parameters.ServiceConnection }}
        ImageName: $(ContainerImageName)
        BranchToCreateLatestTag: master
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: tests/Test-Api.ps1
        pwsh: pwsh
      displayName: Integration Test