stages:
- stage: ApiBuild
  displayName: Build Image
  jobs:
  - job: build_image
    displayName: Build Image
    pool:
      name: DAS - Continuous Integration
      demands:
        - docker
    steps:
      - task: UseGitVersion@5
        inputs:
          versionSpec: 5.x
          useConfigFile: true
          configFilePath: GitVersion.yml

      - task: Docker@2
        displayName: Login to Docker Hub
        inputs:
          command: login
          containerRegistry: Apprenticeships DevOps Docker Hub

      - task: Docker@2
        displayName: Build Image
        inputs:
          command: build
          dockerfile: Dockerfile
          repository: apprenticeshipsdevops/das-tools-notifications
          tags: $(Build.BuildNumber)

      - task: Docker@2
        displayName: Push Image
        inputs:
          command: push
          repository: apprenticeshipsdevops/das-tools-notifications
          tags: $(Build.BuildNumber)
