parameters:
  ServiceConnection:

stages:
- stage: ApiBuild
  displayName: Build Image
  jobs:
  - job: build_image
    displayName: Build Image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UseDocker@0
      displayName: Use Docker
      inputs:
        dockerVersion: 20.10.x

    - script: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
      displayName: Install docker-compose

    - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

    - template: azure-pipelines-templates/build/step/dockerfile-build.yml@das-platform-building-blocks
      parameters:
        ContainerRegistryName: $(PublicAcrName)
        ServiceConnection: ${{ parameters.ServiceConnection }}
        ImageName: $(ContainerImageName)
        BranchToCreateLatestTag: master

    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: tests/Test-Api.ps1
        pwsh: pwsh
      displayName: Integration Test

    - template: azure-pipelines-templates/build/step/nuget-pack.yml@das-platform-building-blocks
      parameters:
        DotNetStandardPackagesToPack: |
          src/SFA.DAS.ToolsNotifications.Client/SFA.DAS.ToolsNotifications.Client.csproj;
          src/SFA.DAS.ToolsNotifications.Types/SFA.DAS.ToolsNotifications.Types.csproj
