stages:
- stage: PackageBuild
  displayName: Build Package
  jobs:
  - job: build_package
    displayName: Build Package
    pool:
      name: DAS - Continuous Integration
    steps:
    - task: UseGitVersion@5
      inputs:
        versionSpec: 5.x
        useConfigFile: true
        configFilePath: GitVersion.yml

    - task: DotNetCoreCLI@2
      displayName: dotnet restore
      inputs:
        command: restore
        projects: src/SFA.DAS.ToolsNotifications.Client/SFA.DAS.ToolsNotifications.Client.csproj

    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
        projects: src/SFA.DAS.ToolsNotifications.Client/SFA.DAS.ToolsNotifications.Client.csproj
        arguments: --configuration release --no-restore

    - task: DotNetCoreCLI@2
      displayName: dotnet pack
      inputs:
        command: pack
        packagesToPack: src/SFA.DAS.ToolsNotifications.Client/SFA.DAS.ToolsNotifications.Client.csproj
        packDirectory: $(Build.ArtifactStagingDirectory)/package
        versioningScheme: byBuildNumber

    - task: PublishPipelineArtifact@1
      displayName: Publish Artifact - packages
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)/package
        artifactName: NugetPackages