stages:
- stage: PackageBuild
  displayName: Build Package
  jobs:
  - job: build_package
    displayName: Build Package
    steps:
    - task: UseGitVersion@5
      inputs:
        versionSpec: 5.x
        useConfigFile: true
        configFilePath: GitVersion.yml

    - task: DotNetCoreCLI@2
      displayName: dotnet restore
      inputs:
        command: restore
        projects: src/SFA.DAS.ToolsNotifications.Client/SFA.DAS.ToolsNotifications.Client.csproj

    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
        projects: src/SFA.DAS.ToolsNotifications.Client/SFA.DAS.ToolsNotifications.Client.csproj
        arguments: /p:Configuration=Release

    - task: DotNetCoreCLI@2
      displayName: dotnet pack
      inputs:
        command: pack
        projects: src/SFA.DAS.ToolsNotifications.Client/SFA.DAS.ToolsNotifications.Client.csproj
        packDirectory: $(Build.ArtifactStagingDirectory)/package
        versioningScheme: byBuildNumber

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact - packages
      inputs:
        artifactName: package
        pathtoPublish: $(Build.ArtifactStagingDirectory)/package
