version: "3.9"
services:
  web:
    build: .
    network_mode: "host"
    environment:
      RedisConnectionString: 127.0.0.1:6379
      EnvironmentName: LOCAL
      ASPNETCORE_ENVIRONMENT: Development
  redis:
    image: "redis:alpine"