version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      RedisConnectionString: redis:6379
      EnvironmentName: LOCAL
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:alpine"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
