---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: das-tool-notifications-api
  namespace: {{KubernetesNamespace}}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: {{TlsSecretName}}
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/health-probe-path: "/health"
spec:
  rules:
  - host: {{IngressHost}}
    http:
      paths:
      - path: /api/notifications
        pathType: Exact
        backend:
          service:
            name: das-tools-notifications
            port:
              number: 80
